name: Event Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-event:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Determine the event type
      - name: Determine Event Type
        id: event_type
        run: echo "EVENT_TYPE=${{ github.event_name }}" >> $GITHUB_ENV

      # Step 2: Push-only step
      - name: Push Event Step
        if: env.EVENT_TYPE == 'push'
        run: echo "This is a push event."

      # Step 3: Pull Request-only step
      - name: Pull Request Event Step
        if: env.EVENT_TYPE == 'pull_request'
        run: echo "This is a pull request event."
